// This file is computer-generated by onnx2c 
// Command Line: /workspace/build/onnx2c -p im2col /workspace/test/simple_networks/conv_2kernels_randombias.onnx -f conv_2kernels_randombias_im2col

// onnx2c
// Git Branch: 123-img2col
// Git Commit: ea045cc

// ONNX Model
// Produced By: keras2onnx, version 1.7.0
// ONNX IR version: 11

#include <float.h>
#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>

#define MAX(X,Y) ( X > Y ? X : Y)
#define MIN(X,Y) ( X < Y ? X : Y)
#define CLIP(X,L) ( MAX(MIN(X,L), -L) )

#if __STDC_VERSION__ < 199901L
#define FUNC_PREFIX
#else
#define FUNC_PREFIX static inline
#endif

static const float tensor_conv2d_kernel_0[2][1][2][2] = 
{
  {
    {
      {1.00000000000000000000f, 1.00000000000000000000f},
      {1.00000000000000000000f, 1.00000000000000000000f}
    }
  },
  {
    {
      {1.00000000000000000000f, 1.00000000000000000000f},
      {1.00000000000000000000f, 1.00000000000000000000f}
    }
  }
};
static const float tensor_conv2d_bias_0[2] = 
{0.07490351051092147827f, -0.03121598437428474426f};
static float tensor_adjusted_input[1][1][5][5];
static float tensor_convolution_output[1][2][4][4];
static float tensor_push_transpose_out_0[1][4][4][2];
static const int64_t tensor_im2col_const_0[3] = 
{1, 4, 16};
static float tensor_conv2d_reshape_x_output[1][4][16];
static const int64_t tensor_im2col_const_1[2] = 
{2, 4};
static float tensor_conv2d_reshape_w_output[2][4];
static float tensor_conv2d_matmul_mm_output[1][2][16];
static float tensor_conv2d_add_bias_output[1][2][16];
static const int64_t tensor_im2col_const_2[4] = 
{1, 2, 4, 4};
static float tensor_conv2d_reshape_y_output[1][2][4][4];

/*
 * Operand:           Transpose
 * Name in ONNX file: Transpose
 */
FUNC_PREFIX void node_Transpose( const float input[1][5][5][1], float output[1][1][5][5] )
{
	/* Transpose
	 * perm = 0 3 1 2 
	 */
	for( uint32_t i0=0; i0<1; i0++ ) {
	for( uint32_t i1=0; i1<5; i1++ ) {
	for( uint32_t i2=0; i2<5; i2++ ) {
	for( uint32_t i3=0; i3<1; i3++ ) {
		output[i0][i3][i1][i2] = input[i0][i1][i2][i3];
	}
	}
	}
	}
}

/*
 * Operand:           Transpose
 * Name in ONNX file: PushTranspose_0
 */
FUNC_PREFIX void node_PushTranspose_0( const float input[1][2][4][4], float output[1][4][4][2] )
{
	/* Transpose
	 * perm = 0 2 3 1 
	 */
	for( uint32_t i0=0; i0<1; i0++ ) {
	for( uint32_t i1=0; i1<2; i1++ ) {
	for( uint32_t i2=0; i2<4; i2++ ) {
	for( uint32_t i3=0; i3<4; i3++ ) {
		output[i0][i2][i3][i1] = input[i0][i1][i2][i3];
	}
	}
	}
	}
}

/*
 * Operand:           Flatten
 * Name in ONNX file: flatten
 */
FUNC_PREFIX void node_flatten( const float input[1][4][4][2], float output[1][32] )
{
	/* Flatten*/
	float *input_ = (float*)input;
	float *output_ = (float*)output;
	for( uint32_t i=0; i<32; i++ )
		output_[i] = input_[i];

}

/*
 * Operand:           Reshape
 * Name in ONNX file: conv2d_reshape_x
 */
FUNC_PREFIX void node_conv2d_reshape_x( const float data[1][1][5][5], const int64_t shape[3], float reshaped[1][4][16] )
{
	/*Reshape*/
	float *data_ptr = (float*)data;
	float *reshaped_ptr = (float*)reshaped;
	uint32_t i;
	for( i=0; i<25; i++ )
		reshaped_ptr[i] = data_ptr[i];

}

/*
 * Operand:           Reshape
 * Name in ONNX file: conv2d_reshape_w
 */
FUNC_PREFIX void node_conv2d_reshape_w( const float data[2][1][2][2], const int64_t shape[2], float reshaped[2][4] )
{
	/*Reshape*/
	float *data_ptr = (float*)data;
	float *reshaped_ptr = (float*)reshaped;
	uint32_t i;
	for( i=0; i<8; i++ )
		reshaped_ptr[i] = data_ptr[i];

}

/*
 * Operand:           MatMul
 * Name in ONNX file: conv2d_matmul_mm
 */
FUNC_PREFIX void node_conv2d_matmul_mm( const float A[1][4][16], const float B[2][4], float Y[1][2][16] )
{
	/* MatMul (AbstractMatMul) */
	for (unsigned i0=0; i0<1; i0++)
	{
		for (unsigned i = 0; i < 4; i++)
		for (unsigned j = 0; j < 4; j++)
		{
			Y[i0][i][j] = 0;
			for (unsigned k = 0; k < 16; k++)
			{
				Y[i0][i][j] += A[0][i][k] * B[k][j];
			}
		}
	}
}

/*
 * Operand:           Add
 * Name in ONNX file: conv2d_add_bias
 */
FUNC_PREFIX void node_conv2d_add_bias( const float a[1][2][16], const float b[2], float c[1][2][16] )
{
	/* Add
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	for (unsigned i0=0; i0<1; i0++)
	for (unsigned i1=0; i1<2; i1++)
	for (unsigned i2=0; i2<16; i2++)
	{
		C[0][i1][i2] = A[0][i1][i2]+B[i2];;
	}
}

/*
 * Operand:           Reshape
 * Name in ONNX file: conv2d_reshape_y
 */
FUNC_PREFIX void node_conv2d_reshape_y( const float data[1][2][16], const int64_t shape[4], float reshaped[1][2][4][4] )
{
	/*Reshape*/
	float *data_ptr = (float*)data;
	float *reshaped_ptr = (float*)reshaped;
	uint32_t i;
	for( i=0; i<32; i++ )
		reshaped_ptr[i] = data_ptr[i];

}


void conv_2kernels_randombias_im2col(const float tensor_conv2d_input[1][5][5][1], float tensor_flatten[1][32]){
	node_Transpose( tensor_conv2d_input, tensor_adjusted_input);
	node_PushTranspose_0( tensor_conv2d_reshape_y_output, tensor_push_transpose_out_0);
	node_flatten( tensor_push_transpose_out_0, tensor_flatten);
	node_conv2d_reshape_x( tensor_adjusted_input, tensor_im2col_const_0, tensor_conv2d_reshape_x_output);
	node_conv2d_reshape_w( tensor_conv2d_kernel_0, tensor_im2col_const_1, tensor_conv2d_reshape_w_output);
	node_conv2d_matmul_mm( tensor_conv2d_reshape_x_output, tensor_conv2d_reshape_w_output, tensor_conv2d_matmul_mm_output);
	node_conv2d_add_bias( tensor_conv2d_matmul_mm_output, tensor_conv2d_bias_0, tensor_conv2d_add_bias_output);
	node_conv2d_reshape_y( tensor_conv2d_add_bias_output, tensor_im2col_const_2, tensor_conv2d_reshape_y_output);
}
