// This file is computer-generated by onnx2c 
// Command Line: /workspace/build/onnx2c /workspace/test/simple_networks/conv_2kernels.onnx -f conv_2kernels_regular

// onnx2c
// Git Branch: 123-img2col
// Git Commit: ea045cc

// ONNX Model
// Produced By: keras2onnx, version 1.7.0
// ONNX IR version: 11

#include <float.h>
#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>

#define MAX(X,Y) ( X > Y ? X : Y)
#define MIN(X,Y) ( X < Y ? X : Y)
#define CLIP(X,L) ( MAX(MIN(X,L), -L) )

#if __STDC_VERSION__ < 199901L
#define FUNC_PREFIX
#else
#define FUNC_PREFIX static inline
#endif

static const float tensor_conv2d_kernel_0[2][1][2][2] = 
{
  {
    {
      {1.00000000000000000000f, 1.00000000000000000000f},
      {1.00000000000000000000f, 1.00000000000000000000f}
    }
  },
  {
    {
      {1.00000000000000000000f, 1.00000000000000000000f},
      {1.00000000000000000000f, 1.00000000000000000000f}
    }
  }
};
static const float tensor_conv2d_bias_0[2] = 
{0.00000000000000000000f, 0.00000000000000000000f};
union tensor_union_0 {
float tensor_adjusted_input[1][1][5][5];
float tensor_push_transpose_out_0[1][4][4][2];
};
static union tensor_union_0 tu0;

union tensor_union_1 {
float tensor_convolution_output[1][2][4][4];
};
static union tensor_union_1 tu1;


/*
 * Operand:           Transpose
 * Name in ONNX file: Transpose
 */
FUNC_PREFIX void node_Transpose( const float input[1][5][5][1], float output[1][1][5][5] )
{
	/* Transpose
	 * perm = 0 3 1 2 
	 */
	for( uint32_t i0=0; i0<1; i0++ ) {
	for( uint32_t i1=0; i1<5; i1++ ) {
	for( uint32_t i2=0; i2<5; i2++ ) {
	for( uint32_t i3=0; i3<1; i3++ ) {
		output[i0][i3][i1][i2] = input[i0][i1][i2][i3];
	}
	}
	}
	}
}

/*
 * Operand:           Conv
 * Name in ONNX file: conv2d
 */
FUNC_PREFIX void node_conv2d( const float x[1][1][5][5], const float w[2][1][2][2], const float bias[2], float y[1][2][4][4] )
{
	/* Conv
	 *
	 * auto_pad: VALID
	 * dilations: 1 1 
	 * group: 1
	 * kernel_shape: 2 2 
	 * pads: 0 0 0 0 
	 * strides: 1 1 
	 */
	for( uint32_t b=0; b<1; b++ ) {
	for( uint32_t m=0; m<2; m++) {
		for( int32_t o0=0, i0=0; o0<4; o0++, i0+=1) {
		for( int32_t o1=0, i1=0; o1<4; o1++, i1+=1) {
			y[b][m][o0][o1] = bias[m];
			for( int32_t c=0; c<1; c++ ) {
			for( uint32_t k0=0; k0<2; k0++ ) {
			for( uint32_t k1=0; k1<2; k1++ ) {
				int ii0 = i0+k0 * 1;
				int ii1 = i1+k1 * 1;
				y[b][m][o0][o1] += x[b][c][ii0][ii1] * w[m][c][k0][k1];
			} /* k */
			} /* k */
			} /* c */
		} /* o */
		} /* o */
	} /* m */
	} /* b */
}

/*
 * Operand:           Transpose
 * Name in ONNX file: PushTranspose_0
 */
FUNC_PREFIX void node_PushTranspose_0( const float input[1][2][4][4], float output[1][4][4][2] )
{
	/* Transpose
	 * perm = 0 2 3 1 
	 */
	for( uint32_t i0=0; i0<1; i0++ ) {
	for( uint32_t i1=0; i1<2; i1++ ) {
	for( uint32_t i2=0; i2<4; i2++ ) {
	for( uint32_t i3=0; i3<4; i3++ ) {
		output[i0][i2][i3][i1] = input[i0][i1][i2][i3];
	}
	}
	}
	}
}

/*
 * Operand:           Flatten
 * Name in ONNX file: flatten
 */
FUNC_PREFIX void node_flatten( const float input[1][4][4][2], float output[1][32] )
{
	/* Flatten*/
	float *input_ = (float*)input;
	float *output_ = (float*)output;
	for( uint32_t i=0; i<32; i++ )
		output_[i] = input_[i];

}


void conv_2kernels_regular(const float tensor_conv2d_input[1][5][5][1], float tensor_flatten[1][32]){
	node_Transpose( tensor_conv2d_input, tu0.tensor_adjusted_input);
	node_conv2d( tu0.tensor_adjusted_input, tensor_conv2d_kernel_0, tensor_conv2d_bias_0, tu1.tensor_convolution_output);
	node_PushTranspose_0( tu1.tensor_convolution_output, tu0.tensor_push_transpose_out_0);
	node_flatten( tu0.tensor_push_transpose_out_0, tensor_flatten);
}
